services:
  web:
    build: .
    ports:
      - "80:4000"
    depends_on:
      - redis
    logging:
      driver: gcplogs
  redis:
    image: "redis:alpine"
    logging:
      driver: gcplogs
